//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceKZ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceKZ() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceKZ", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жаңа жазба қосу.
        /// </summary>
        internal static string AddNewRec {
            get {
                return ResourceManager.GetString("AddNewRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тапсырмалар.
        /// </summary>
        internal static string Assignments {
            get {
                return ResourceManager.GetString("Assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жаппай аяқталу күні.
        /// </summary>
        internal static string BulkEndDate {
            get {
                return ResourceManager.GetString("BulkEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жаппай басталу күні.
        /// </summary>
        internal static string BulkStartDate {
            get {
                return ResourceManager.GetString("BulkStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РЕЗЮМЕ.
        /// </summary>
        internal static string CVLink {
            get {
                return ResourceManager.GetString("CVLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бөлімнің жеке куәлігі.
        /// </summary>
        internal static string DepartmentID {
            get {
                return ResourceManager.GetString("DepartmentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бөлімнің атауы.
        /// </summary>
        internal static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мақсаты:.
        /// </summary>
        internal static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Толық жүктелген:.
        /// </summary>
        internal static string FullLoaded {
            get {
                return ResourceManager.GetString("FullLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тапсыру күні.
        /// </summary>
        internal static string GrdAsingmentDateOfAssignemnt {
            get {
                return ResourceManager.GetString("GrdAsingmentDateOfAssignemnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жобаның атауы.
        /// </summary>
        internal static string GrdAsingmentProjectName {
            get {
                return ResourceManager.GetString("GrdAsingmentProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ресурстың атауы.
        /// </summary>
        internal static string GrdAsingmentResourceName {
            get {
                return ResourceManager.GetString("GrdAsingmentResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тапсырма түрінің атауы.
        /// </summary>
        internal static string GrdAsingmentTypeName {
            get {
                return ResourceManager.GetString("GrdAsingmentTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аяқталу күні.
        /// </summary>
        internal static string GrdEndDate {
            get {
                return ResourceManager.GetString("GrdEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Басталатын күн.
        /// </summary>
        internal static string GrdStartDate {
            get {
                return ResourceManager.GetString("GrdStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жұмыс жүктемесі.
        /// </summary>
        internal static string GrdWorkload {
            get {
                return ResourceManager.GetString("GrdWorkload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жоқ.
        /// </summary>
        internal static string LabelTextNo {
            get {
                return ResourceManager.GetString("LabelTextNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Иә.
        /// </summary>
        internal static string LabelTextYes {
            get {
                return ResourceManager.GetString("LabelTextYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тіл.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/metis_login.png.
        /// </summary>
        internal static string LoginIMG {
            get {
                return ResourceManager.GetString("LoginIMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шығу.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аты.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Қызметкерлер саны:.
        /// </summary>
        internal static string NoEmployee {
            get {
                return ResourceManager.GetString("NoEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Артық жүктелген:.
        /// </summary>
        internal static string Overloaded {
            get {
                return ResourceManager.GetString("Overloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ішінара жүктелген:.
        /// </summary>
        internal static string PartiallyLoaded {
            get {
                return ResourceManager.GetString("PartiallyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль:.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жобаның қысқаша мазмұны.
        /// </summary>
        internal static string ProjectSummary {
            get {
                return ResourceManager.GetString("ProjectSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Есеп беру.
        /// </summary>
        internal static string ReportTo {
            get {
                return ResourceManager.GetString("ReportTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ресурстың қысқаша мазмұны.
        /// </summary>
        internal static string ResourceSummary {
            get {
                return ResourceManager.GetString("ResourceSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рөл атауы.
        /// </summary>
        internal static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сүзгі элементін көрсету.
        /// </summary>
        internal static string ShowFilterItemText {
            get {
                return ResourceManager.GetString("ShowFilterItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тарихты көрсету.
        /// </summary>
        internal static string ShowHistory {
            get {
                return ResourceManager.GetString("ShowHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Күй.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streebo exp:.
        /// </summary>
        internal static string Streebo {
            get {
                return ResourceManager.GetString("Streebo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жалпы эксп:.
        /// </summary>
        internal static string TotalExp {
            get {
                return ResourceManager.GetString("TotalExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жүктелген:.
        /// </summary>
        internal static string Underloaded {
            get {
                return ResourceManager.GetString("Underloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пайдалану пайызы (таңдалған кезең үшін):.
        /// </summary>
        internal static string UtilizePersentage {
            get {
                return ResourceManager.GetString("UtilizePersentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пайдалану пайызы (Келесі 4 апта):.
        /// </summary>
        internal static string UtilizePersentage4Week {
            get {
                return ResourceManager.GetString("UtilizePersentage4Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пайдалану пайызы (Келесі.
        /// </summary>
        internal static string UtlizePersonNext {
            get {
                return ResourceManager.GetString("UtlizePersonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Апта):.
        /// </summary>
        internal static string weeks {
            get {
                return ResourceManager.GetString("weeks", resourceCulture);
            }
        }
    }
}
