//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceRU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceRU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceRU", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новую запись.
        /// </summary>
        internal static string AddNewRec {
            get {
                return ResourceManager.GetString("AddNewRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назначения.
        /// </summary>
        internal static string Assignments {
            get {
                return ResourceManager.GetString("Assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Массовая дата окончания.
        /// </summary>
        internal static string BulkEndDate {
            get {
                return ResourceManager.GetString("BulkEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Массовая дата начала.
        /// </summary>
        internal static string BulkStartDate {
            get {
                return ResourceManager.GetString("BulkStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать только доступный ресурс.
        /// </summary>
        internal static string CheckBoxText {
            get {
                return ResourceManager.GetString("CheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РЕЗЮМЕ.
        /// </summary>
        internal static string CVLink {
            get {
                return ResourceManager.GetString("CVLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ресурстарды бөлуді көрсету.
        /// </summary>
        internal static string DDLShowResourceAll {
            get {
                return ResourceManager.GetString("DDLShowResourceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ресурстың қол жетімділігін көрсету.
        /// </summary>
        internal static string DDLShowResourceAvail {
            get {
                return ResourceManager.GetString("DDLShowResourceAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор отдела.
        /// </summary>
        internal static string DepartmentID {
            get {
                return ResourceManager.GetString("DepartmentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to название отдела.
        /// </summary>
        internal static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обозначение:.
        /// </summary>
        internal static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полная загрузка:.
        /// </summary>
        internal static string FullLoaded {
            get {
                return ResourceManager.GetString("FullLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата назначения.
        /// </summary>
        internal static string GrdAsingmentDateOfAssignemnt {
            get {
                return ResourceManager.GetString("GrdAsingmentDateOfAssignemnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to название проекта.
        /// </summary>
        internal static string GrdAsingmentProjectName {
            get {
                return ResourceManager.GetString("GrdAsingmentProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название ресурса.
        /// </summary>
        internal static string GrdAsingmentResourceName {
            get {
                return ResourceManager.GetString("GrdAsingmentResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя типа назначения.
        /// </summary>
        internal static string GrdAsingmentTypeName {
            get {
                return ResourceManager.GetString("GrdAsingmentTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата окончания.
        /// </summary>
        internal static string GrdEndDate {
            get {
                return ResourceManager.GetString("GrdEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата начала.
        /// </summary>
        internal static string GrdStartDate {
            get {
                return ResourceManager.GetString("GrdStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нагрузка.
        /// </summary>
        internal static string GrdWorkload {
            get {
                return ResourceManager.GetString("GrdWorkload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нет.
        /// </summary>
        internal static string LabelTextNo {
            get {
                return ResourceManager.GetString("LabelTextNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to да.
        /// </summary>
        internal static string LabelTextYes {
            get {
                return ResourceManager.GetString("LabelTextYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to язык.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/metis_login.png.
        /// </summary>
        internal static string LoginIMG {
            get {
                return ResourceManager.GetString("LoginIMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to название.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет сотрудников:.
        /// </summary>
        internal static string NoEmployee {
            get {
                return ResourceManager.GetString("NoEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перегруженный:.
        /// </summary>
        internal static string Overloaded {
            get {
                return ResourceManager.GetString("Overloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частично загружен:.
        /// </summary>
        internal static string PartiallyLoaded {
            get {
                return ResourceManager.GetString("PartiallyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль:.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое описание проекта.
        /// </summary>
        internal static string ProjectSummary {
            get {
                return ResourceManager.GetString("ProjectSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщить в.
        /// </summary>
        internal static string ReportTo {
            get {
                return ResourceManager.GetString("ReportTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резюме ресурса.
        /// </summary>
        internal static string ResourceSummary {
            get {
                return ResourceManager.GetString("ResourceSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя роли.
        /// </summary>
        internal static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать элемент фильтрации.
        /// </summary>
        internal static string ShowFilterItemText {
            get {
                return ResourceManager.GetString("ShowFilterItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать историю.
        /// </summary>
        internal static string ShowHistory {
            get {
                return ResourceManager.GetString("ShowHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Положение дел.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streebo exp:.
        /// </summary>
        internal static string Streebo {
            get {
                return ResourceManager.GetString("Streebo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего опыта:.
        /// </summary>
        internal static string TotalExp {
            get {
                return ResourceManager.GetString("TotalExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to недогруженном:.
        /// </summary>
        internal static string Underloaded {
            get {
                return ResourceManager.GetString("Underloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процент использования (за выбранный период):.
        /// </summary>
        internal static string UtilizePersentage {
            get {
                return ResourceManager.GetString("UtilizePersentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процент использования (следующие 4 недели):.
        /// </summary>
        internal static string UtilizePersentage4Week {
            get {
                return ResourceManager.GetString("UtilizePersentage4Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процент использования (следующий.
        /// </summary>
        internal static string UtlizePersonNext {
            get {
                return ResourceManager.GetString("UtlizePersonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недели):.
        /// </summary>
        internal static string weeks {
            get {
                return ResourceManager.GetString("weeks", resourceCulture);
            }
        }
    }
}
